### ISSUE TITLE
package the online player list on right.

### ISSUE THREAD

**Issue by pironic** [overviewer/Minecraft-Overviewer-Addons#1]
https://github.com/brownan/Minecraft-Overviewer/issues/324

**Comment by pyrodogg** [comment]
I was curious and checking issues when I noticed this link is a 404.  Here's the update from the account switch

https://github.com/Overviewer/Minecraft-Overviewer/issues/324

**Comment by pironic** [comment]
https://github.com/overviewer/Minecraft-Overviewer-Addons/tree/master/PlayerMarkers

completed.
