### ISSUE TITLE
Polygonal Region Support?

### ISSUE THREAD

**Issue by weirdbeard** [overviewer/Minecraft-Overviewer-Addons#3]
This mod does not appear to support polygonal regions from WorldEdit 4.5/WorldGuard 5. Am I correct? If so, I'd like to suggest adding support for them. Thanks for a great mod!

**Comment by pironic** [comment]
I wasn't aware that worldedit supported polygon regions... I'll look into this and come up with a fix.

pi's notes:
http://wiki.sk89q.com/wiki/WorldEdit/Selection#Selecting_Polygons
not actual 3d polygons... they are only 2d with hgih and low. which means there can't be more than 2 vertical points. ex: L can't exist unless its on its side...

**Comment by pironic** [comment]
i just pushed some work i've done with polygons to the master branch. It now "supports" polygon regions in a sence... and for that im going to close the issue. But improving the drawing of these polygons will continue to exist on my todo list. 

i need to spend some time thinking about how we want to draw the isometric portion of the polygons, but for now it will render at most the top and bottom of the shape you made (unless of course the shape is less than 3m high, in which case it'll cut the difference and render 1 flat polygon in the middle of your shape)

feel free to post any idea's on how we should render the shapes now that the topic is closed.

**Comment by pironic** [comment]
you should take a look in the polygon branch now... looks great now :-) still not done though.

**Comment by weirdbeard** [comment]
Thanks, pironic! I have not had a chance to try this out yet but I appreciate your efforts. I will have a look as soon as I can. -WB

**Comment by pironic** [comment]
http://minecraft.writhem.com/dev/ :-)

Michael Writhe
WritheM Web Solutions
michael@writhem.com
