### ISSUE TITLE
Missing repeaters in the ExMaplE map.

### ISSUE THREAD

**Issue by Fenixin** [overviewer/Minecraft-Overviewer-Addons#4]
Would be great to have all the possible combinations of repeaters in the test map, I mean, for each orientation all the possible delays.

At the moment all the delays are shown only for north orientation. I think there's no need for also differentiate between on and off states right now, so it can be fixed adding 2 more repeater-crosses and each of the repeaters in the cross with the same delay (just an idea, if you make it, do it your way).

**Comment by pironic** [comment]
added, published :)
