### ISSUE TITLE
new blocks. 1.6

### ISSUE THREAD

**Issue by pironic** [overviewer/Minecraft-Overviewer-Addons#5]
we need new blocks.
- tall grass (31:1F) - can use bonemeal to add it
- dead shrub (32:20)
- hatch (96:60)
- map (358:166)

**Comment by pironic** [comment]
trees on north edge need to be removed, should move the dead shrub as well cause its blocked by the cliff.

**Comment by Fenixin** [comment]
Thanks for the update!

I can't run MCedit in mi own computer (it refuses to run). I'll try to add some stuff when I get other computer.
